# Generated by Django 3.1.1 on 2022-04-07 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0002_auto_20220407_0901'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['surname']},
        ),
    ]
